# *- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "redhat0#{i}" do |node|
      node.vm.box = "generic/rhel8"
      node.vm.hostname = "redhat0#{i}.example.com"
      node.vm.network "private_network", ip: "172.42.42.10#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "redhat0#{i}"
        v.memory = 4096
        v.cpus = 2
      end
    end
  end

end